### ISSUE TITLE
Multiple plugin in single dbt project

### ISSUE THREAD

**Issue by grawatadsk** [dbt-labs/homebrew-dbt#382]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I'm trying to add multiple plugin dbt-snowflake and  dbt-redshift. but while checking dbt --version . It is showing that only one plugin is their

```
dbt --version
Core:
  - installed: 1.5.10
  - latest:    1.7.10 - Update available!

  Your version of dbt-core is out of date!
  You can find instructions for upgrading here:
  https://docs.getdbt.com/docs/installation

Plugins:
  - snowflake: 1.5.6 - Update available!

  At least one plugin is out of date or incompatible with dbt-core.
  You can find instructions for upgrading here:
  https://docs.getdbt.com/docs/installation`
```

### Environment

```markdown
- OS:
- Python:
- dbt:
```

**Comment by dbeatty10** [comment]
Thanks for reaching out @grawatadsk. 

Could you share the commands you are using to install dbt-core, dbt-snowflake, and dbt-redshift ?

If you are using `pip`, then I'd expect your command to look something like [this](https://docs.getdbt.com/docs/core/pip-install) (assuming you've already created and activated a virtual environment, if desired):
```shell
python -m pip install dbt-core dbt-snowflake dbt-redshift
```

Or something like this to install the latest patch release of dbt v1.7:
```shell
python -m pip install dbt-core=~1.7.0 dbt-snowflake=~1.7.0 dbt-redshift=~1.7.0
```

**Comment by grawatadsk** [comment]
I'm using brew command ,

bew install dbt-core dbt-snowflake dbt-redshift 

But its not connecting to plugin. 
`
Core:
  - installed: 1.5.10
  - latest:    1.7.10 - Update available!

  Your version of dbt-core is out of date!
  You can find instructions for upgrading here:
  https://docs.getdbt.com/docs/installation

Plugins:
  - snowflake: 1.5.6 - Update available!

  At least one plugin is out of date or incompatible with dbt-core.
  You can find instructions for upgrading here:
  https://docs.getdbt.com/docs/installation`

**Comment by dbeatty10** [comment]
Ah, I see!

We [stopped maintaining Homebrew](https://docs.getdbt.com/docs/core/homebrew-install) as a supported installation method for dbt-core and adapters starting with starting in version 1.6.0. More info here:
- [Installing dbt Core: saying goodbye to brew and hello to "bundles"](https://github.com/dbt-labs/dbt-core/discussions/8277)

The `dbt-core-bundles` repo contains our replacement mechanism, and you can read more details [here](https://github.com/dbt-labs/dbt-core-bundles?tab=readme-ov-file#how-to-use).

Alternatively, you can install via one of the other mechanisms listed [here](https://docs.getdbt.com/docs/core/installation-overview#install-dbt-core).

Since we don't support `brew install dbt-snowflake`, etc. anymore, I'm going to close this issue as "not planned".
