### ISSUE TITLE
Problem installing dbt with homebrew - no matching distribution found for setuptools-rust

### ISSUE THREAD

**Issue by rjelzinga** [dbt-labs/homebrew-dbt#50]
Followed the instructions here https://docs.getdbt.com/dbt-cli/installation#homebrew but keep getting this error
```
Last 15 lines from /Users/relzinga/Library/Logs/Homebrew/dbt/23.pip:
        eps = map(lambda e: e.load(), pkg_resources.iter_entry_points(group))
      File "/usr/local/opt/python@3.8/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2449, in load
        self.require(*args, **kwargs)
      File "/usr/local/opt/python@3.8/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2472, in require
        items = working_set.resolve(reqs, env, installer, extras=self.extras)
      File "/usr/local/opt/python@3.8/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pkg_resources/__init__.py", line 772, in resolve
        raise DistributionNotFound(req, requirers)
    pkg_resources.DistributionNotFound: The 'six' distribution was not found and is required by packaging
    ----------------------------------------
  WARNING: Discarding https://files.pythonhosted.org/packages/97/ba/339c9ff979f3ceb8206b12a10d84bc048da642ac355fa68cd28d4c19f465/setuptools-rust-0.11.4.tar.gz#sha256=9714fcb94c78e6ab1864ddac7750049e105fd4f7c52103aecf40d408e94a722f (from https://pypi.org/simple/setuptools-rust/). Command errored out with exit status 1: /usr/local/Cellar/dbt/0.21.0_1/libexec/bin/python3 /private/tmp/tmprmjijh8x prepare_metadata_for_build_wheel /private/tmp/tmpv9z6kihk Check the logs for full command output.
  ERROR: Could not find a version that satisfies the requirement setuptools-rust>=0.11.4 (from versions: 0.1, 0.2, 0.3, 0.3.1, 0.4, 0.4.1, 0.4.2, 0.5.0, 0.5.1, 0.6.0, 0.6.1, 0.6.2, 0.6.3, 0.6.4, 0.7.0, 0.7.1, 0.7.2, 0.8.0, 0.8.1, 0.8.2, 0.8.3, 0.8.4, 0.9.0, 0.9.1, 0.9.2, 0.10.0, 0.10.1, 0.10.2, 0.10.3, 0.11.0, 0.11.1, 0.11.2b0, 0.11.2, 0.11.3, 0.11.4, 0.11.5, 0.11.6, 0.12.0, 0.12.1, 1.0.0)
  ERROR: No matching distribution found for setuptools-rust>=0.11.4
  Installing build dependencies: finished with status 'error'
WARNING: Discarding file:///private/tmp/dbt--cryptography-20211123-81778-xv51nv/cryptography-3.4.8. Command errored out with exit status 1: /usr/local/Cellar/dbt/0.21.0_1/libexec/bin/python3 /private/tmp/pip-standalone-pip-m9irricz/__env_pip__.zip/pip install --ignore-installed --no-user --prefix /private/tmp/pip-build-env-09m7n5mo/overlay --no-warn-script-location --no-binary :all: --only-binary :none: -i https://pypi.org/simple -- 'setuptools>=40.6.0' wheel 'cffi>=1.12; platform_python_implementation != '"'"'PyPy'"'"'' 'setuptools-rust>=0.11.4' Check the logs for full command output.
ERROR: Command errored out with exit status 1: /usr/local/Cellar/dbt/0.21.0_1/libexec/bin/python3 /private/tmp/pip-standalone-pip-m9irricz/__env_pip__.zip/pip install --ignore-installed --no-user --prefix /private/tmp/pip-build-env-09m7n5mo/overlay --no-warn-script-location --no-binary :all: --only-binary :none: -i https://pypi.org/simple -- 'setuptools>=40.6.0' wheel 'cffi>=1.12; platform_python_implementation != '"'"'PyPy'"'"'' 'setuptools-rust>=0.11.4' Check the logs for full command output.

If reporting this issue please do so at (not Homebrew/brew or Homebrew/core):
  https://github.com/dbt-labs/homebrew-dbt/issues
```

**Comment by bmckenna88** [comment]
I'm also unable to install dbt with homebrew - but because of no matching disto found for setuptools

Using pip 21.3.1 from /usr/local/Cellar/dbt-bigquery/1.0.0/libexec/lib/python3.9/site-packages/pip (python 3.9)
Processing /private/tmp/dbt-bigquery--mashumaro-20211208-13577-13s8498/mashumaro-2.9
  Installing build dependencies: started
  Running command /usr/local/Cellar/dbt-bigquery/1.0.0/libexec/bin/python3.9 /private/tmp/pip-standalone-pip-_tu4h8kc/__env_pip__.zip/pip install --ignore-installed --no-user --prefix /private/tmp/pip-build-env-crh25wxd/overlay --no-warn-script-location --no-binary :all: --only-binary :none: -i https://pypi.org/simple -- 'setuptools>=40.8.0' wheel
  WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x10e3dbd60>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /simple/setuptools/
  WARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x10e667d00>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /simple/setuptools/
  WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x10e367160>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /simple/setuptools/
  WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x10e367910>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /simple/setuptools/
  WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x10e367a30>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /simple/setuptools/
  ERROR: Could not find a version that satisfies the requirement setuptools>=40.8.0 (from versions: none)
  ERROR: No matching distribution found for setuptools>=40.8.0
  Installing build dependencies: finished with status 'error'

**Comment by bmckenna88** [comment]
I was able to install with pip

**Comment by andreu7d** [comment]
Same here, different error structure, but looks to be the same
`Last 15 lines from /Users/andre/Library/Logs/Homebrew/dbt-snowflake@1.0.0-b1/18.pip:
  × pip subprocess to install build dependencies did not run successfully.
  │ exit code: 1
  ╰─> See above for output.
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  full command: /usr/local/Cellar/dbt-snowflake@1.0.0-b1/1.0.0b1/libexec/bin/python3.9 /private/tmp/pip-standalone-pip-sipnevlf/__env_pip__.zip/pip install --ignore-installed --no-user --prefix /private/tmp/pip-build-env-54kscimt/overlay --no-warn-script-location --no-binary :all: --only-binary :none: -i https://pypi.org/simple -- 'setuptools>=40.6.0' wheel 'cffi>=1.12; platform_python_implementation != '"'"'PyPy'"'"'' 'setuptools-rust>=0.11.4'
  cwd: [inherit]
  Installing build dependencies: finished with status 'error'
error: subprocess-exited-with-error

× pip subprocess to install build dependencies did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.`

**Comment by kyleries** [comment]
@ChenyuLInx - not sure what the process is for handling stale issues, but I think this has likely since been resolved, and is further improved via https://github.com/dbt-labs/homebrew-dbt/pull/161 .

**Comment by ChenyuLInx** [comment]
@kyleries Yes, I would think so. We can close it for now and reopen if it becomes a issue again.
