### ISSUE TITLE
Getting metadata-generation-failed error for dbt_extractor-0.2.0 when brew installing dbt@0.20.0

### ISSUE THREAD

**Issue by ken-drsq** [dbt-labs/homebrew-dbt#82]
I am running into an issue when brew installing dbt@0.20.0 via `arch -x86_64 brew install dbt@0.20.0`.
I get the following error:

```
^ZLast 15 lines from /Users/user/Library/Logs/Homebrew/dbt@0.20.0/23.pip:
 × Preparing metadata (pyproject.toml) did not run successfully.
 │ exit code: 1
 ╰─> See above for output.
  
 note: This error originates from a subprocess, and is likely not a problem with pip.
 full command: /usr/local/Cellar/dbt@0.20.0/0.20.0_1/libexec/bin/python3 /usr/local/Cellar/dbt@0.20.0/0.20.0_1/libexec/lib/python3.8/site-packages/pip/_vendor/pep517/in_process/_in_process.py prepare_metadata_for_build_wheel /private/tmp/tmpn4f5xv76
 cwd: /private/tmp/dbtA0.20.0--dbt-extractor-20220322-51447-zbkwfi/dbt_extractor-0.2.0
 Preparing metadata (pyproject.toml): finished with status 'error'
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

## Expected Behavior

The installation should complete with no errors

## Current Behavior

The installation halts when the above error appears, doing `dbt --version` after shows that dbt was not installed at all.

## Possible Solution

Based on [this ticket](https://github.com/dbt-labs/dbt-core/issues/4891), it seems like the solution may be to update the dbt-extractor [here](https://github.com/dbt-labs/homebrew-dbt/blob/main/Formula/dbt@0.20.0.rb) (and for other relevant dbt versions)

## Steps to Reproduce

1. Created a new python environment on M1 Macbook Pro (macOS Monterey Version 12.2), `python3 --version` returns python 3.8.9
2. Opened a Rosetta terminal
3. Ran `arch -x86_64 /bin/bash -c "$(curl -fsSL[ https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh](https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh))"`, was successful
4. Ran `brew tap dbt-labs/dbt` on 03/22/2022, was successful
5. Ran `arch -x86_64 brew install dbt@0.20.0`, encountered error mentioned above

## Context (Environment)

I am currently setting up dbt for the first time on a brand new Macbook Pro

**Comment by ken-drsq** [comment]
Hi @jtcohen6, I'm a little new around here! Would you be able to let me know what the bug and triage label mean? Is there a typical timeline/course of action for these issues?

**Comment by jtcohen6** [comment]
Hey @ken-drsq! These labels are part of our OSS maintenance process, to make sure the appropriate team is aware of the issue, and so that they can give you a timely response. At the same time, over the past few months, we've been actively revamping our OSS maintenance practices.

My aim is to always reflect those practices, and set clear expectations for contributors, in the `dbt-core` contributing guide. For instance, this section details our use of issue labels: https://github.com/dbt-labs/dbt-core/blob/main/CONTRIBUTING.md#using-issue-labels

I've got some work slated for myself, to update that doc: https://github.com/dbt-labs/docs.getdbt.com/issues/1057

I'm going to leave the `triage` label in place, so that someone from the "Core - Execution" team can take a further look here. At first glance, I see that you're installing dbt v0.20.0, on an M1 architecture via Rosetta, and running into an issue with the `dbt-extractor` package. If you are able to upgrade to dbt-core v1.0, it upgrades the dependency to `dbt-extractor==0.4.0`, which supports (I believe) a pre-built wheel for the M1 native architecture.
